version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-flask-app
    container_name: my-flask-app
    ports:
      - "5003:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1